Adding VARCHAR type to mini-runners and random fixes
cmu-db/noisepage pull request #1169
Opened 2020-09-10 03:42 UTC by malin1993ml

This PR mainly augments the mini-runners to support the VARCHAR type for sequential scans and index scans. For now, all the varchars are inlined because dealing with memory management with non-inlined varchars requires additional engineering.

Other random changes/fixes:
1. Extend the bwtree index template to support 512-byte key.
2. Extend the global trainer to support data collected with sampling.
3. Fix the data size calculation for `SEQ_SCAN` in `operating_unit_recorder`.
4. Adjust the key size calculation for VARCHARs in `operating_unit_recorder`.

2020-09-10 18:02 UTC, 17zhangw requested changes
Generally LGTM! Just some minor clarification on whether some changes should be committed.

2020-09-10 22:44 UTC, malin1993ml commented on src/include/main/db_main.h
> +      if (metrics_pipeline_) metrics_manager->EnableMetric(metrics::MetricsComponent::EXECUTION_PIPELINE, 9);
I think let's do this. This avoids the metrics collection having too much overhead to affect the system behavior itself, especially in concurrent OLTP workloads. I'm using this even in the single-threaded setting now to get a consistent measurement, though the prediction accuracy looks similar to recording everything.

2020-09-10 22:45 UTC, malin1993ml commented on script/model/mini_trainer.py
> +    aparser.add_argument('--save_path', default='trained_model_varchar', help='Path to save the mini models')
Those paths are a bit random anyway... but you're correct that the changes are unnecessary.

2020-09-11 01:51 UTC, 17zhangw approved these changes
LGTM

2020-09-11 01:53 UTC, merged