Fix having cluases in aggregates
cmu-db/noisepage pull request #1310
Opened 2020-11-08 22:37 UTC by jkosh44

## Description

When building the physical plan of an aggregate expression the group
by columns are hard coded into the output tuple 0, and the aggregate
values are hard coded into the output tuple 1.

When we were evaluating the output schema, we were saving the results
of all the columns in a SINGLE map of expression to value index. This
map was later used in ExpressionUtil::EvaluateExpression and
ExpressionUtil::ConverExprCVNodes to derive the Value Tuples of the
having clause.

The issue was that the above two functions take a list of maps, where
each map corresponds to a single tuple, and the index of the map in
the list is the tuple index. Therefore we needed two seperate maps,
one map for tuple 0 which contained the group by columns and one map
for tuple 1 which contained the aggregate values.

Fixes #1222 

## Remaining tasks

- [ ] Add Tests

## Performance
N/A

## Further work
- I'm pretty sure there may be some room for performance improvements in `ConverExprCVNodes`. I'm going to open a separate issue

2020-11-09 07:25 UTC, lmwnshn requested changes
Nice! Could you please add some of your PR description into BuildAggregatePlan? e.g. where the two maps are defined, "this is why we need the maps..."

2020-11-09 15:14 UTC, jkosh44 commented
> Nice! Could you please add some of your PR description into BuildAggregatePlan? e.g. where the two maps are defined, "this is why we need the maps..."

@lmwnshn Done. I'm not super happy about the wording of the comment so if you have any improvements feel free to change it or comment. The PR description is also in the commit message so at least it will be available to anyone who blames the file or checks the history.

2020-11-09 15:33 UTC, lmwnshn commented
The commit messages are hidden since we squash (otherwise we would have lots of "lint" "lint" "format" "tidy" "FORMAT" commit messages). But yea, they'll be in this PR. Thanks!

2020-11-09 15:37 UTC, jkosh44 commented
Do you mean that when we squash the commits we get rid of everything but the header? I understand removing the useless messages but I think that having some description with a commit can be useful when looking through the history.

2020-11-09 15:52 UTC, lmwnshn commented
I think it is less get rid of everything but the header, and more there was no particularly good description to begin with (see current commits). I think PRs like yours are a good candidate for "let's start merging some PRs with descriptions"

2020-11-09 15:58 UTC, jkosh44 commented
I read [this](https://chris.beams.io/posts/git-commit/) awhile back at work and try and use it to guide my commit messages.

Anyway it looks like a jumbotest is consistently failing so I'm going to look into that.

2020-11-09 16:45 UTC, jkosh44 commented
Jumbo Tests seem to be failing for two different reasons, though each run seems random as to which one causes the failure

1. Socket issue
```
[network_logger] [error] Failed to bind networked socket: Address already in use
unknown file: Failure
C++ exception with description "Failed to bind networked socket." thrown in SetUp().
[  FAILED  ] CatalogSqlTests.OptimizerHashmapTest (981 ms)
```
This is happening in another unrelated PR so I don't think this is related to this PR: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1243/57/tests
2. `malloc_consolidate(): invalid chunk size` Which is an existing issue: https://github.com/cmu-db/noisepage/issues/1261

2020-11-10 20:13 UTC, lmwnshn approved these changes
LGTM, pending @17zhangw comments.

2020-11-10 20:37 UTC, 17zhangw commented
LGTM. Nice!

2020-11-10 20:37 UTC, 17zhangw approved these changes

2020-11-11 16:31 UTC, merged