Fix for issue #1220 : Added support for order by for aggregate expressions
cmu-db/noisepage pull request #1321
Opened 2020-11-10 21:36 UTC by gautam20197

This is a fix for #1220 

Changes in the PR:

1. Binder: Added binding of order by columns using alias by picking from the select list. If the alias does not exist in the select list, the binder will throw an error of the column not existing.

2. Optimizer: Create a derived value expression from children expression of the aggregate expression that will be sorted by the order by.

2020-11-11 21:07 UTC, lmwnshn requested changes
Could you remove the dead code? Will help you generate the trace files later.

2020-11-11 21:07 UTC, lmwnshn commented on src/binder/bind_node_visitor.cpp
> +//    bool alias_unified = UnifyAliasNameOrderByExpression(node->GetSelectOrderBy(), node->GetSelectColumns());
Dead code.

2020-11-11 21:09 UTC, gautam20197 commented on src/binder/bind_node_visitor.cpp
> +//    bool alias_unified = UnifyAliasNameOrderByExpression(node->GetSelectOrderBy(), node->GetSelectColumns());
Yup I'll do that.

2020-11-11 21:17 UTC, lmwnshn commented
Additionally, you may need to run format/tidy/etc first.

2020-11-19 06:05 UTC, lmwnshn approved these changes
LGTM if passes CI.

2020-11-19 13:10 UTC, merged